FROM treqster/tiles:dev

COPY ./maps/hikebikemap-carto/ /map/
COPY ./pg.mml.patch ./pg.mml.patch
RUN cartocc /map/project.mml ./pg.mml.patch  > /map/local_project.mml
RUN carto /map/local_project.mml > /map/mapnik.xml

COPY ./prepare-hikebikemap-carto.sh /map/build.sh
VOLUME /map/data

