version: '3.1'
services:
  tiles:
    image: treqster/tiles:dev
    build: .
    volumes:
      - ./data/openstreetmap-carto/:/data/
      - ./src/:/opt/app/
    ports:
      - "18888:8000"

  hikebikemap-carto:
    image: treqster/hikebikemap-carto:dev
    build:
      context: .
      dockerfile: Dockerfile-hikebikemap-carto
    volumes:
      - ./tmp/openstreetmap-carto/:/map/data/
      - ./src/:/opt/app/
    environment:
      POSTGRES_HOST: "osmpg"
      POSTGRES_DB: "hikebikemapcarto"
      POSTGRES_USER: "osm"
    ports:
      - "18888:8000"

  hikebikemap-carto-builder:
    image: treqster/hikebikemap-carto:dev
    build:
      context: .
      dockerfile: Dockerfile-hikebikemap-carto
    volumes:
      - ./tmp/openstreetmap-carto/:/map/data/
      - ./src/:/opt/app/
      - ./prepare-hikebikemap-carto.sh:/data/build.sh
    environment:
      POSTGRES_HOST: "osmpg"
      POSTGRES_DB: "hikebikemapcarto"
      POSTGRES_USER: "osm"
    command: /data/build.sh
    restart: "no"

  openstreetmap-carto:
    image: treqster/openstreetmap-carto:dev
    build:
      context: .
      dockerfile: Dockerfile-openstreetmap-carto
    volumes:
      - ./tmp/openstreetmap-carto/:/map/data/
      - ./src/:/opt/app/
    environment:
      POSTGRES_HOST: "osmpg"
      POSTGRES_DB: "openstreetmapcarto"
      POSTGRES_USER: "osm"
    ports:
      - "18888:8000"

  openstreetmap-carto-builder:
    image: treqster/openstreetmap-carto:dev
    build:
      context: .
      dockerfile: Dockerfile-openstreetmap-carto
    volumes:
      - ./tmp/openstreetmap-carto/:/map/data/
      - ./src/:/opt/app/
      - ./prepare-openstreetmap-carto.sh:/data/build.sh
    environment:
      POSTGRES_HOST: "osmpg"
      POSTGRES_DB: "openstreetmapcarto"
      POSTGRES_USER: "osm"
    command: /data/build.sh
    restart: "no"


  opentopomap:
    image: treqster/openstopomap:dev
    build:
      context: .
      dockerfile: Dockerfile-opentopomap
    volumes:
      - ./tmp/opentopomap/:/map/data/
      - ./src/:/opt/app/
    environment:
      POSTGRES_HOST: "osmpg"
      POSTGRES_DB: "openstopomap"
      POSTGRES_USER: "osm"


  opentopomap-builder:
    image: treqster/openstopomap:dev
    build:
      context: .
      dockerfile: Dockerfile-opentopomap
    volumes:
      - ./tmp/opentopomap/:/map/data/
      - ./src/:/opt/app/
      - ./prepare-openstopomap.sh:/data/build.sh
    environment:
      POSTGRES_HOST: "osmpg"
      POSTGRES_DB: "openstopomap"
      POSTGRES_USER: "osm"
    command: /data/build.sh
    restart: "no"



  osmpg:
    image: treqster/postgis-osm
    build:
      context: .
      dockerfile: ./postgis-osm/Dockerfile
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
#      POSTGRES_DB: "osm"
      POSTGRES_DBS: "openstreetmapcarto hikebikemapcarto opentopomap"
      POSTGRES_USER: "osm"
      POSTGRES_PASSWORD: ""


volumes:
  pgdata:

